# Site settings
title: Xixiong Guo
SEOTitle: Xixiong Blog
header-img: img/home-bg-o.jpg
email: guoxixiong1991@gmail.com
description: "Aspiring data scientist"
keyword: "data science"
url: "https://Xixiong-Guo.github.io"              # your host, for absolute URL
baseurl: ""                  # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     owenshine
#zhihu_username:     UWOSh7ne
#github_username:    Sh7ne
#twitter_username:   UWOSh7ne
#facebook_username:  UWOSh7ne
#linkedin_username:  Sh7ne           #linkedin.com/in/your username here#



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: Xixiong Guo
# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: ''            # Format: UA-xxxxxx-xx
ga_domain: Xixiong-Guo.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
#sidebar-avatar: /img/IMG_8434.JPG       # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "Something",
#        href: "http://something.com/"
#    },{
#        title: "aha",
#        href: "http://aha.aha/"
#    }
       
#]
